.storybook/storybook-components/icons-table/icons-table.module.scss
src/components/badge/badge.module.scss
src/components/badge/badge.stories.tsx
src/components/badge/badge.tsx
src/components/filled-badge/filled-badge.module.scss
src/components/general-alerts/general-alerts.module.scss
src/components/menu/menu.module.scss
src/components/message-panel/message-panel.module.scss
src/components/modal/modal.module.scss
src/components/popup/popup.module.scss
src/components/spinner/spinner.module.scss
src/components/table/expandable-table/row-expander/row-expander.module.scss
src/components/table/table.module.scss
src/components/tabs/tabs.module.scss
src/components/tooltip/tooltip.module.scss
src/forms/form-group/form-group.module.scss
src/forms/inputs/button/button.module.scss
src/forms/inputs/button/cancel-button/cancel-button.module.scss
src/forms/inputs/button/link-button/link-button.module.scss
src/forms/inputs/checkbox/checkbox.module.scss
src/forms/inputs/dropdown-input/dropdown-input.module.scss
src/forms/inputs/dropdown/dropdown.module.scss
src/forms/inputs/input/input.module.scss
src/forms/inputs/textarea/textarea.module.scss
src/forms/inputs/toggler/toggler.module.scss
src/forms/inputs/toggler/toggler.stories.tsx
src/layouts/section/section.module.scss
src/style-guide/_colors.scss

EPMDJ-2489: Update the color palette in ui-kit

---

src/components/index.ts
src/components/table-filter/__snapshots__/table-filter.spec.tsx.snap
src/components/table-filter/index.ts
src/components/table-filter/table-filter.module.scss
src/components/table-filter/table-filter.spec.tsx
src/components/table-filter/table-filter.stories.tsx
src/components/table-filter/table-filter.tsx
src/components/table-filter/use-filter.spec.ts
src/components/table-filter/use-filter.ts
src/forms/inputs/checkbox/checkbox.module.scss
src/forms/inputs/checkbox/checkbox.tsx

EPMDJ-2523: Сreate a component for Filtering with checkboxes

---

src/components/table-filter/use-filter.ts
src/components/table/__snapshots__/selectable-table.spec.tsx.snap
src/forms/inputs/checkbox/__snapshots__/checkbox.spec.tsx.snap
src/forms/inputs/checkbox/checkbox-types.ts
src/forms/inputs/checkbox/checkbox.module.scss
src/forms/inputs/checkbox/checkbox.stories.tsx
src/forms/inputs/checkbox/checkbox.tsx

EPMDJ-2541: Add support for the different colors for the checkbox

---

README.md

EPMDJ-3054: Update readme.md for ui-kit

---

package.json
src/forms/inputs/textarea/textarea-types.ts
src/forms/inputs/textarea/textarea.module.scss
src/forms/inputs/textarea/textarea.stories.tsx

EPMDJ-3571: Update textarea styles

---

package-lock.json
package.json
src/components/message-panel/message-panel.module.scss
src/components/message-panel/message-panel.stories.tsx

EPMDJ-3854 Update system and general alerts

---

src/components/sort-arrows/__snapshots__/sort-arrows.spec.tsx.snap
src/components/sort-arrows/sort-arrows.module.scss
src/components/sort-arrows/sort-arrows.tsx

EPMDJ-4330: Fix console warning on Test2Code Page

---

package.json
src/components/additional-progress-bar/additional-progress-bar.module.scss
src/components/main-progress-bar/main-progress-bar.module.scss

EPMDJ-4842: Update main progress bar animation

---

.storybook/preview-body.html
package.json
src/components/modal/modal.stories.tsx
src/components/modal/modal.tsx
src/components/popup/popup.tsx
src/components/portal/portal.tsx
src/components/tooltip/__snapshots__/tooltip.spec.tsx.snap
src/components/tooltip/get-tooltip-position.spec.ts
src/components/tooltip/get-tooltip-position.ts
src/components/tooltip/tooltip.module.scss
src/components/tooltip/tooltip.spec.tsx
src/components/tooltip/tooltip.stories.tsx
src/components/tooltip/tooltip.tsx

EPMDJ-3047: Update Tooltip and Portal components

---

package.json
src/components/general-alerts/general-alerts.tsx

Refactoring: Update GeneralAlerts error icon

---

package.json
src/forms/inputs/button/link-button/link-button.module.scss

EPMDJ-5376: Update link button display

---

package.json
src/components/legend/__snapshots__/legend.spec.tsx.snap
src/components/legend/legend.module.scss
src/components/legend/legend.stories.tsx
src/components/legend/legend.tsx

EPMDJ-5540: Update legend

---

package.json
src/components/popup/popup.module.scss
src/components/popup/popup.stories.tsx

EPMDJ-5570: Improve header popup font-size

---

package-lock.json
package.json
src/components/table/expandable-table/expandable-table.tsx
src/components/table/table.tsx

EPMDJ-5796: Update expanded table

---

package.json
src/components/table/table.module.scss

EPMDJ-5796: Update table font size

---

package.json
src/forms/inputs/textarea/__snapshots__/textarea.spec.tsx.snap
src/forms/inputs/textarea/textarea-types.ts
src/forms/inputs/textarea/textarea.module.scss
src/forms/inputs/textarea/textarea.tsx

EPMDJ-5958: Update textarea

---

package.json
src/components/spinner/spinner.module.scss
src/components/spinner/spinner.stories.tsx
src/components/spinner/spinner.tsx

EPMDJ-5980: Update spinner

---

package.json
src/components/tooltip/tooltip.module.scss
src/components/tooltip/tooltip.stories.tsx

EPMDJ-6036: Update tooltip

---

package.json
src/components/message-panel/message-panel.tsx
src/components/table/table-row.module.scss
src/components/table/table.tsx
src/components/table/table__row.tsx
src/forms/inputs/button/button.module.scss
src/forms/inputs/button/button.stories.tsx
src/forms/inputs/button/link-button/link-button.module.scss

EPMDJ-6058: Update system alert, buttons, expanded table

---

package.json
src/forms/inputs/input/input.module.scss
src/forms/inputs/textarea/textarea.module.scss

EPMDJ-6119: Update input colors

---

package.json
src/components/table/default-header-cell.tsx

EPMDJ-6149: Update sort table logic

---

package.json
src/components/menu/menu.module.scss

EPMDJ-6276: Update menu styles

---

package.json
src/components/table/table.tsx

EPMDJ-6367: Add unique key for table rows

---

package.json
src/forms/inputs/button/button.module.scss

EPMDJ-6139: Change disabled button opacity

---

package-lock.json
package.json
src/__mocks__/intersectionObserverMock.ts
src/components/menu/menu.module.scss
src/components/menu/menu.spec.tsx
src/components/menu/menu.tsx
yarn.lock

EPMDJ-6587: remove visibility sensor from menu component

---

package.json
src/components/modal/modal.tsx
src/forms/inputs/checkbox/__snapshots__/checkbox.spec.tsx.snap
src/forms/inputs/dropdown/__snapshots__/dropdown.spec.tsx.snap

EPMDJ-7137: Add dinamic modal width

---

package.json
src/components/spinner/__snapshots__/spinner.spec.tsx.snap
src/components/spinner/spinner.tsx
src/forms/inputs/button/__snapshots__/button.spec.tsx.snap
src/forms/inputs/button/button.tsx
src/forms/inputs/button/cancel-button/__snapshots__/cancel-button.spec.tsx.snap
src/forms/inputs/button/link-button/__snapshots__/link-button.spec.tsx.snap
src/forms/inputs/button/negative-action-button/__snapshots__/negative-action-button.spec.tsx.snap

EPMDJ-6934: Update button gap and spinner color

---

package-lock.json
package.json
src/forms/fields/field.tsx
src/forms/fields/index.ts
src/forms/fields/use-preserve-caret-position.ts
src/forms/fields/use-run-after-update.ts
src/forms/form-validators/form-validators.spec.ts
src/forms/form-validators/form-validators.ts
src/forms/form-validators/index.ts
src/index.ts

EPMDJ-7828: Add fields and form-validators

---

package.json
src/components/general-alerts/__snapshots__/general-alerts.spec.tsx.snap
src/components/general-alerts/general-alerts.tsx
src/components/index.ts
src/components/stub/index.ts
src/components/stub/stub.tsx
src/forms/inputs/checkbox/__snapshots__/checkbox.spec.tsx.snap
src/forms/inputs/dropdown/__snapshots__/dropdown.spec.tsx.snap

EPMDJ-7842: Add stub component

---

src/components/table/table-elements.ts
src/components/table/table.stories.tsx
src/components/table/table.tsx

- Add props that control search displaying
- Add z-index for header

EPMDJ-7978: Table improvements

---

package-lock.json
package.json
src/components/forms/inputs/search-input/search-input.tsx

EPMDJ-8185: Remove search input border

---

package.json
src/components/menu/menu.tsx

fix: the menu is overlapped table header

---

package.json
src/components/forms/inputs/textarea/textarea-types.ts
src/components/forms/inputs/textarea/textarea.tsx
src/components/table/pagination.tsx
src/components/table/table-elements.ts

EPMDJ-8217: Fix displaying menu under table header

---

package-lock.json
package.json
src/components/modal/modal.tsx

EPMDJ-7137: Remove possibility change width of panel

---

package.json
src/components/table/table.tsx

EPMDJ-8155: add necessary keys in table

---

package-lock.json
package.json
src/components/table/pagination-elements.ts
src/components/table/pagination.tsx
src/components/table/table.tsx

EPMDJ-7978: Fix pagination select page modal styles

---

package.json
src/components/forms/index.ts
src/components/index.ts
src/drill4j-ui-kit.ts

EPMDJ-7410: export FromValidator

---

package-lock.json
package.json
src/components/text-overflow-center/text-overflow-center.stories.tsx
src/drill4j-ui-kit.ts

EPMDJ-8390: Add middle text-overflow-ellipsis

---

.storybook/preview-body.html
package-lock.json
package.json

EPMDJ-8415: Import system js

---

package.json
src/components/table/table-elements.ts
src/components/table/table.tsx

EPMDJ-8407: Fix table paddings

---

package.json
src/components/table/table.tsx

EPMDJ-7978: Fix "GO TO" goes to page N+1 when there are only N pages

---

package-lock.json
src/components/table/table.stories.tsx
src/components/table/table.tsx

EPMDJ-8457: Add ellipsis for td

---

package.json
src/components/table/table.tsx

EPMDJ-6149: Add sort by default in table

---

package.json
src/components/forms/form-validators/form-validators.ts

EPMDJ-7977: Fix positiveInteger error message

---

package.json
src/components/forms/form-validators/form-validators.ts

EPMDJ-7977: Fix validation positiveInteger logiс on empty value
